version: "3.7"

services:
  proxy: 
    image: traefik:1.5
    ports:
      - "8080:8080"
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localnet
    command: --entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443 TLS' --defaultEntryPoints=http,https --docker --docker.watch --docker.exposedbydefault=false  --web 
 
networks:
  localnet:
    external: true

