version: "3.7"
  
services:
  nodejs:
    image: node:8-alpine
    networks:
      - localnet
      - default
    command: tail -f /dev/null
    volumes:
      - ../../app:/app
      - ./docker-runtime/node_modules:/app/node_modules
    labels:
      - "traefik.docker.network=localnet"
      - "traefik.frontend.rule=Host:nodejs.workshop.loc"
      - "traefik.enable=true"
      - "traefik.port=4200"

networks:
  localnet:
    external: true
